Team = enum {
  red;
  blue;
}

RepositionEvent = record {
  team: Team;
  point: i32;
  x: i32;
  y: i32;
}

UISettings = record {
  left: i32;
  top: i32;
  right: i32;
  bottom: i32;
  spacing: i32;
}

RepositionListener = interface +o +j {
  onReposition(e: RepositionEvent);
}

Game = interface +c {
  static create(uiSettings: UISettings, totalPoints: i32): Game;
  getPointSize(): i32;
  setRepositionListener(l: RepositionListener);
  startGame();
  gainPoint(t: Team);
  losePoint(t: Team);
}
