Team = enum {
  red;
  blue;
}

PointsCanvasMetrics = record {
  left: i32;
  top: i32;
  right: i32;
  bottom: i32;
  spacing: i32;
}

PointCreationEvent = record {
  team: Team;
  id: i32;
  x: i32;
  y: i32;
  size: i32;
}

PointRepositionEvent = record {
  team: Team;
  id: i32;
  x: i32;
  y: i32;
}

PointListener = interface +o +j {
  onCreation(e: PointCreationEvent);
  onReposition(e: PointRepositionEvent);
}

Game = interface +c {
  static create(metrics: PointsCanvasMetrics, totalPoints: i32, l: PointListener): Game;
  gainPoint(t: Team);
  losePoint(t: Team);
}
