PROJECT_NAME='DjinniDemo'
MAIN_HEADER_FILE="ios_project/$PROJECT_NAME/$PROJECT_NAME-Bridging-Header.h"
MAIN_MM_FILE="ios_project/$PROJECT_NAME/$PROJECT_NAME-Bridging-Header.mm"

echo "//" > $MAIN_HEADER_FILE
echo "//  This file is automatically generated in order to import djinni generated Objective-C++ public headers into Swift project." >> $MAIN_HEADER_FILE
echo "//  Do not modify this file. Changes are revoked after make command execution." >> $MAIN_HEADER_FILE
echo "//" >> $MAIN_HEADER_FILE
echo "" >> $MAIN_HEADER_FILE

echo "//" > $MAIN_MM_FILE
echo "//  This file is automatically generated in order to import djinni generated Objective-C++ public headers into Swift project." >> $MAIN_MM_FILE
echo "//  Do not modify this file. Changes are revoked after make command execution." >> $MAIN_MM_FILE
echo "//" >> $MAIN_MM_FILE
echo "" >> $MAIN_MM_FILE
echo "#import \"$PROJECT_NAME-Bridging-Header.h\"" >> $MAIN_MM_FILE

for PUBLIC_HEADER in `cd generated-src/objc && ls *.h | grep -v "+Private" && cd - > /dev/null`
do
  echo "#import \"$PUBLIC_HEADER\"" >> $MAIN_HEADER_FILE
done
